emovie_search:
    resource: "@EmovieSearchBundle/Controller/"
    type:     annotation
    prefix:   /

emovie_corporative:
    resource: "@EmovieCorporativeBundle/Controller/"
    type:     annotation
    prefix:   /

#emovie_rating:
#    resource: "@EmovieRatingBundle/Controller/"
#    type:     annotation
#    prefix:   /

#emovie_user:
#    resource: "@EmovieUserBundle/Controller/"
#    type:     annotation
#    prefix:   /

emovie_movie:
    resource: "@EmovieMovieBundle/Controller/"
    type:     annotation
    prefix:   /

# Sonata Admin Bundle
admin:
    resource: '@SonataAdminBundle/Resources/config/routing/sonata_admin.xml'
    prefix: /admin

_sonata_admin:
    resource: .
    type: sonata_admin
    prefix: /admin

# FOS User Bundle
fos_user_security:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"

fos_user_profile:
    resource: "@FOSUserBundle/Resources/config/routing/profile.xml"
    prefix: /profile

fos_user_register:
    resource: "@FOSUserBundle/Resources/config/routing/registration.xml"
    prefix: /register

fos_user_resetting:
    resource: "@FOSUserBundle/Resources/config/routing/resetting.xml"
    prefix: /resetting

fos_user_change_password:
    resource: "@FOSUserBundle/Resources/config/routing/change_password.xml"
    prefix: /profile

# Internal routing configuration to handle ESI
# ****** WARNING ******
# This route should be enabled with caution as it can open a security vulnerability
# see http://symfony.com/blog/security-release-symfony-2-0-20-and-2-1-5-released for more information
# ****** WARNING ******
#_internal:
#    resource: "@FrameworkBundle/Resources/config/routing/internal.xml"
#    prefix:   /_internal
